-- backup of att_res_flse_lim (real seed; --clear-faults restores from here)
-- generated by inject_missing_flood_limit; demo restore script.
SET NAMES utf8mb4;
INSERT INTO att_res_flse_lim (id, flse_lim_stag, flood_season_name, flood_season_start, flood_season_end, res_guid, create_time, update_time, collect_time, creator, updater, tenant_id) VALUES ('1', '461.500', '前汛期', '0501', '0630', 'BFA0027855X', '2026-06-08 19:06:57.000000', NULL, NULL, NULL, NULL, '18');
INSERT INTO att_res_flse_lim (id, flse_lim_stag, flood_season_name, flood_season_start, flood_season_end, res_guid, create_time, update_time, collect_time, creator, updater, tenant_id) VALUES ('2', '462.500', '主汛期', '0701', '0831', 'BFA0027855X', '2026-06-08 19:06:57.000000', NULL, NULL, NULL, NULL, '18');
INSERT INTO att_res_flse_lim (id, flse_lim_stag, flood_season_name, flood_season_start, flood_season_end, res_guid, create_time, update_time, collect_time, creator, updater, tenant_id) VALUES ('3', '462.000', '后汛期', '0901', '1015', 'BFA0027855X', '2026-06-08 19:06:57.000000', NULL, NULL, NULL, NULL, '18');
